// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQvz0ICzr0bl_EhBDxI6fbTLfc_64T2TI',
    appId: '1:1060492570258:web:b2739f6d81622529e0404b',
    messagingSenderId: '1060492570258',
    projectId: 'leopolis-060320',
    authDomain: 'leopolis-060320.firebaseapp.com',
    storageBucket: 'leopolis-060320.firebasestorage.app',
    measurementId: 'G-1YYPMEWZFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCmd9ZDjP62NT-l7oi1j2c4DOKGxrhNY',
    appId: '1:1060492570258:android:62b3ccc47273bc3ae0404b',
    messagingSenderId: '1060492570258',
    projectId: 'leopolis-060320',
    storageBucket: 'leopolis-060320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGyBikom2z041gIGc9mczx5Uwdk_FirvM',
    appId: '1:1060492570258:ios:d95e3f3067173a3ae0404b',
    messagingSenderId: '1060492570258',
    projectId: 'leopolis-060320',
    storageBucket: 'leopolis-060320.firebasestorage.app',
    iosBundleId: 'com.jorgeasen.leopolis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQvz0ICzr0bl_EhBDxI6fbTLfc_64T2TI',
    appId: '1:1060492570258:web:3beaec6ff2c46957e0404b',
    messagingSenderId: '1060492570258',
    projectId: 'leopolis-060320',
    authDomain: 'leopolis-060320.firebaseapp.com',
    storageBucket: 'leopolis-060320.firebasestorage.app',
    measurementId: 'G-KQTVXXSHK2',
  );
}
